spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: ${TEST_DB_URL:jdbc:mysql://localhost:3306/restaurant_service_test?useUnicode=true&characterEncoding=utf8&connectionTimeZone=UTC&forceConnectionTimeZoneToSession=true}
    username: ${TEST_DB_USERNAME:restaurant_app}
    password: ${TEST_DB_PASSWORD:restaurant_app}
